; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Paperless"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "My Company, Inc."
#define MyAppURL "http://www.example.com/"
#define MyAppExeName "paperless.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{C892CF97-477A-48FD-9168-437585227F52}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={sd}\{#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=E:\upupw\运行库说明.txt
; InfoBeforeFile=E:\upupw\doc\瀹夎鍓?txt
; InfoAfterFile=E:\upupw\运行库说明.txt
OutputDir=E:\
OutputBaseFilename=setup
; SetupIconFile=E:\upupw\htdocs\favicon.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "china"; MessagesFile: "compiler:Languages\china.isl"


[Types]
Name: Full ;Description:"install"; Flags: iscustom;
Name: Compact ;Description:"update";

;组件安装
[Components]
;Name: a1; Description: "安装mysql"; Types: Full ;
;Name: a2; Description: "安装**"; Types : Compact;

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "Tasks_1" ; Description:"安装"; Flags: checkedonce
Name: "Tasks_2" ; Description:"更新"; Flags: unchecked

[Files]
Source: "E:\upupw\psvince.dll"; Flags: dontcopy
Source: "E:\upupw\Apache2\*"; DestDir: "{app}\Apache2\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\upupw\Backup\*"; DestDir: "{app}\Backup\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\upupw\doc\*"; DestDir: "{app}\doc\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\upupw\FileZillaftp\*"; DestDir: "{app}\FileZillaftp\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\upupw\Guard\*"; DestDir: "{app}\Guard\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\upupw\htdocs\paperless\webapp\*"; DestDir: "{app}\htdocs\paperless\webapp\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\upupw\PHP7\*"; DestDir: "{app}\PHP7\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\upupw\Redis\*"; DestDir: "{app}\Redis\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\upupw\upcore\*"; DestDir: "{app}\upcore\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\upupw\xdebug\*"; DestDir: "{app}\xdebug\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\upupw\paperless\ServerDaemon\*"; DestDir: "{app}\paperless\ServerDaemon\"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "E:\upupw\paperless\FileServer\FileServer.exe"; DestDir: "{app}\paperless\FileServer\"; Flags: ignoreversion;
Source: "E:\upupw\paperless\FileServer\Net.dll"; DestDir: "{app}\paperless\FileServer\"; Flags: ignoreversion;
Source: "E:\upupw\paperless\paperlessServer\libCom.dll"; DestDir: "{app}\paperless\paperlessServer\"; Flags: ignoreversion;
Source: "E:\upupw\paperless\paperlessServer\mfc90.dll"; DestDir: "{app}\paperless\paperlessServer\"; Flags: ignoreversion;
Source: "E:\upupw\paperless\paperlessServer\PaperlessServer.exe"; DestDir: "{app}\paperless\paperlessServer\"; Flags: ignoreversion;

Source: "E:\upupw\htdocs\favicon.ico"; DestDir: "{app}\htdocs\"; Flags: ignoreversion;
Source: "E:\upupw\paperless.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\upupw\boot.cmd"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\upupw\paperlessCms.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\upupw\start.cmd"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\upupw\uninstall.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\upupw\运行库说明.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\upupw\updateSql.exe"; DestDir: "{app}"; Flags: ignoreversion

; 安装复制，更新忽略
Source: "E:\upupw\MariaDB\*"; DestDir: "{app}\MariaDB\"; Flags: ignoreversion recursesubdirs createallsubdirs; Tasks: Tasks_1;
Source: "E:\upupw\paperless\FileServer\etc\config.xml"; DestDir: "{app}\paperless\FileServer\etc\"; Flags: ignoreversion; Tasks: Tasks_1;
Source: "E:\upupw\paperless\paperlessServer\etc\config.xml"; DestDir: "{app}\paperless\paperlessServer\etc\"; Flags: ignoreversion; Tasks: Tasks_1;

; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Registry]
; Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "upupw"; ValueData: "{app}\{#MyAppExeName}"
Root: HKLM; Subkey: "SOFTWARE\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "startServer"; ValueData: "{app}\start.cmd"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\boot.cmd"; Flags: nowait runhidden

[UninstallRun]
Filename: "{app}\uninstall.exe"; Flags: nowait runhidden

[Code]
function IsModuleLoaded(modulename: AnsiString ):  Boolean;
external 'IsModuleLoaded@files:psvince.dll stdcall';

// PSVince控件在64位系统（Windows 7/Server 2008/Server 2012）下无法检测到进程，使用下面的函数可以解决。
function IsAppRunning(const FileName : string): Boolean;
var
    FSWbemLocator: Variant;
    FWMIService   : Variant;
    FWbemObjectSet: Variant;
begin
    Result := false;
    try
      FSWbemLocator := CreateOleObject('WBEMScripting.SWBEMLocator');
      FWMIService := FSWbemLocator.ConnectServer('', 'root\CIMV2', '', '');
      FWbemObjectSet := FWMIService.ExecQuery(Format('SELECT Name FROM Win32_Process Where Name="%s"',[FileName]));
      Result := (FWbemObjectSet.Count > 0);
      FWbemObjectSet := Unassigned;
      FWMIService := Unassigned;
      FSWbemLocator := Unassigned;
    except
      if (IsModuleLoaded(FileName)) then
        begin
          Result := false;
        end
      else
        begin
          Result := true;
        end
      end;
end;

  // 关闭进程
function TaskKillProcessByName(const FileName : string): Boolean;
  var
  ResultCode: Integer;
begin
    Exec(ExpandConstant('taskkill.exe'), '/f /im ' + '"' + FileName + '"', '', SW_HIDE,
     ewWaitUntilTerminated, ResultCode);
end;

  // 卸载serverDaemon服务
function TaskShutDownDaemon(): Boolean;
  var
  ResultCode: Integer;
begin
     Exec(ExpandConstant('{app}\paperless\ServerDaemon\ServerDaemon.exe'), ' -d ', '', SW_SHOW,
     ewWaitUntilTerminated, ResultCode)
end;

 // 停止服务
function TaskStopService(const FileName : string): Boolean;
  var
  ResultCode: Integer;
begin
    Exec(ExpandConstant('net.exe'), ' stop ' + '"' + FileName + '"', '', SW_HIDE,
     ewWaitUntilTerminated, ResultCode);
end;

// 卸载脚本
function TaskUninstallShell(): Boolean;
  var
  ResultCode: Integer;
begin
    Exec(ExpandConstant('{app}\uninstall.exe'), '', '', SW_HIDE,
     ewWaitUntilTerminated, ResultCode);
end;

//安装，并在安装前检测程序是否在运行，如果运行先结束进程
function InitializeSetup(): Boolean;
begin
  Result := true;
  if  IsAppRunning('httpd.exe') then
  begin
    if MsgBox('安装程序检测到 {#MyAppName} 正在运行！'#13''#13'单击“是”按钮关闭程序并继续安装；'#13''#13'单击“否”按钮退出安装！', mbConfirmation, MB_YESNO) = IDYES then
    begin
      
      TaskKillProcessByName('{#MyAppExeName}');
      TaskStopService('UPUPW_Apache');
          
          if  IsAppRunning('php.exe') then
          begin
              TaskKillProcessByName('php.exe');
          end;

          if  IsAppRunning('paperlessCms.exe') then
          begin
              TaskKillProcessByName('paperlessCms.exe');
          end;

          if  IsAppRunning('redis-server.exe') then
          begin
              TaskStopService('upupw_redis_a');
          end;

          if  IsAppRunning('mysqld.exe') then
          begin
              TaskStopService('UPUPW_Database_A');
          end;

          if  IsAppRunning('ServerDaemon.exe') then
          begin
              TaskStopService('ServerDaemon');
          end;
      Result:= true;
    end
    else
      Result:= false;
  end;
end;

//卸载，与安装类似
function InitializeUninstall(): Boolean;
  begin
    Result:= true;
    if  IsAppRunning('httpd.exe') then
    begin
      if MsgBox('卸载程序检测到 {#MyAppName} 正在运行！'#13''#13'单击“是”按钮关闭程序并继续卸载；'#13''#13'单击“否”按钮退出卸载！', mbConfirmation, MB_YESNO) = IDYES then
      begin
        TaskKillProcessByName('{#MyAppExeName}');
        TaskKillProcessByName('php.exe');
        TaskKillProcessByName('paperlessCms.exe');
        TaskShutDownDaemon();
        TaskStopService('UPUPW_Apache');
        TaskStopService('upupw_redis_a');
        TaskStopService('UPUPW_Database_A');
        Result:= true;
      end
      else
        Result:= false;
    end;
  end;

